### ISSUE TITLE
Cannot read properties of undefined (reading 'summaryField')

### ISSUE THREAD

**Issue by kyelewis** [exogee-technology/graphweaver#100]
When a field type is a type that isn't in the graphweaver entity map (ie. a type-graphql ObjectType that exists without a graphweaver resolver alongside),  the admin UI fails with "Cannot read properties of undefined (reading 'summaryField')

In the admin UI components, in `generateGqlSelectForEntityFields`:

```
return `${field.name} { id ${relatedEntity.summaryField || ''} }
```

`relatedEntity` is undefined in this case because the list of entities only contains graphweaver entities. 

Suggested short-term fix:

```
return `${field.name} { id ${relatedEntity?.summaryField || ''} }
```

But there might be a better long-term fix around identifying these types of non-graphweaver relationship objects?

**Comment by skeep-exogee** [comment]
Hi @kyelewis,

Thanks for raising this! 

We need to have a plan on how we are going to address "non-graphweaver relationship objects" in general. 

In the short term the solution you propose seems to be a fair. The PR attached addresses the change.

Thanks
