### ISSUE TITLE
Issues importing multiple packages that use graphql-type-json

### ISSUE THREAD

**Issue by kyelewis** [exogee-technology/graphweaver#110]
**Describe the bug**
When importing multiple packages in to a graphweaver project that use `graphql-type-json`, you will get an error when starting the project:

`Error: Schema must contain uniquely named types but contains multiple types named "JSON".`

This occurs because all packages are marked by builder as `external: true` and therefore all import their own copy of `graphql-type-json`

**To Reproduce**
- Create a graphweaver project
- Import two packages that both use `graphql-type-json` internally.
- `graphweaver start`

**Expected behavior**
The error does not occur, and one instance of graphql-type-json is used.

**Actual behavior**
`Error: Schema must contain uniquely named types but contains multiple types named "JSON".`

**Comment by skeep-exogee** [comment]
Hi @kyelewis, can you try something for me, if you create a `./src/.npmrc` file with:

`dedupe-peer-dependents=true`

After running `pnpm i` again and then `pnpm start` does the error disappear for you?

This should hopefully remove any duplicate modules from pnpm.

**Comment by kyelewis** [comment]
Thanks- this helped - we also needed to make sure all of the packages using `graphql-type-json` had graphql in their `peerDependencies` as well,  otherwise pnpm still resolved them differently. Now we only have one source and we're all happy!
