### ISSUE TITLE
Field decorator option: adminOptions -> hideInDetailForm does not reflect in Admin UI

### ISSUE THREAD

**Issue by michaelleighstewart** [exogee-technology/graphweaver#1309]
**Describe the bug**
Setting the option "adminUIOptions -> hideInDetailForm: true" does NOT reflect in the admin UI (ie. it is not hidden)

**To Reproduce**
Example field:
  @Field(() => ISODateStringScalar, { nullable: true, adminUIOptions: { hideInDetailForm: true}})
  created_at?: Date;

**Expected behavior**
Setting this should hide the field in the admin UI

**Actual behavior**
The field is still displayed

**Screenshots or Screencasts**
<img width="1190" alt="Screenshot 2024-11-08 122336" src="https://github.com/user-attachments/assets/feae7150-765a-4efb-b519-9547f61e091c">

**Desktop (please complete the following information):**

- OS and version: Windows 11 Desktop

**Additional context**
N/A

**Comment by thekevinbrown** [comment]
This is now fixed in v2.8.2 🎉
