### ISSUE TITLE
Admin UI crashes on entities that have fields of a non-graphweaver graphql object type.

### ISSUE THREAD

**Issue by kyelewis** [exogee-technology/graphweaver#135]
**Describe the bug**
If your entity has fields on it that are GraphQL Object Types that are not part of another graphweaver resolver, the Admin UI will fail to fetch them properly and return a 400 error with no other data.

**To Reproduce**
- Create a new graphweaver project
- Create an entity
- Add a field to the entity that has a GraphQL Object type that is not controlled by graphweaver.
- Open the entity in the Admin UI.

**Expected behavior**
The Admin UI should continue working, even if it some of the fields are empty or missing.

**Actual behavior**
The admin UI fails and returns a generic "400" error to the user.

If the field is a single item, the error returned is:
```
"Cannot query field \"id\" on type \"OtherType\"."
```

If the field is an array, the error returned is:
```
"Field \"others\" of type \"[OtherType!]!\" must have a selection of subfields. Did you mean \"others { ... }\"?"
```

**Comment by skeep-exogee** [comment]
Thanks @kyelewis we have no tests currently that cover "non-graphweaver" objects so we will need to add those tests along with the fix for this bug.

**Comment by steve-keep** [comment]
Hi @kyelewis we now support the JSON type in the admin UI along with tests in the backend:

https://github.com/exogee-technology/graphweaver/blob/main/src/packages/end-to-end/src/__tests__/api/scalars/graphql-json.ts#L19

If you can try again with version `0.2.10+` and let us know if you still have an issue. Thanks
