### ISSUE TITLE
Table and editor fields show inconsistent values for boolean and GraphQLJSON

### ISSUE THREAD

**Issue by kyelewis** [exogee-technology/graphweaver#136]
**Describe the bug**
In the Admin UI, the table view and the editor show different values for the same data

- For GraphQLJSON, the table view shows a JSON string of the data, but the editor shows [object Object].
- For boolean, the table view shows empty if the value is true, but the editor shows 'true'.

**Comment by skeep-exogee** [comment]
Another good catch thanks @kyelewis. We need to handle these cases and also many to many relationships. 

We will prioritise a fix.
