### ISSUE TITLE
maybe misuse of `eslint-plugin-oxlint`

### ISSUE THREAD

**Issue by Sysix** [exogee-technology/graphweaver#1368]
Hello,

you are using the eslint plugin `eslint-plugin-oxlint`. 
This plugin **disables** all the rules, which are currently supported by [oxlint](https://www.npmjs.com/package/oxlint).

I do not see any implementation of `oxlint`. [It should run before eslint](https://github.com/oxc-project/eslint-plugin-oxlint/blob/main/README.md#run-it-before-eslint).

**Comment by thekevinbrown** [comment]
This came from an example during the migration to flat config files. You’re correct, I’ll remove it. Thanks for the heads up!
