### ISSUE TITLE
`graphweaver build` fails if graphweaver is not already running

### ISSUE THREAD

**Issue by kyelewis** [exogee-technology/graphweaver#137]
**Describe the bug**
The `graphweaver build` command fails on type generation step if graphweaver is not already running.

**To Reproduce**
Create a graphweaver project.
Run `graphweaver build`

**Expected behavior**
The build completes.

**Actual behavior**
The type generation steps fail.
```  
Failed to load schema from graphweaver:
request to http://localhost:9001/ failed, reason: connect ECONNREFUSED ::1:9001
```

**Comment by skeep-exogee** [comment]
Thanks @kyelewis this is because the schema uses the running server to generate the files. Ideally, we need to generate the schema file then use this with the build. 

We will look at getting this fixed an make sure we have a test to cover it.

**Comment by kyelewis** [comment]
@skeep-exogee could there be an option to disable schema generation, or do we even need to generate the schema at build time at all?

**Comment by skeep-exogee** [comment]
Yeah we could also have the option to disable the type generation which is causing this bug.

**Comment by siowhoi** [comment]
Hi @kyelewis, this issue has been fixed. Thanks for reporting it.
