### ISSUE TITLE
"Cannot determine GraphQL input type" on filter using RelationshipField, when the target entity class name does not match the name provided in its ObjectType()

### ISSUE THREAD

**Issue by kyelewis** [exogee-technology/graphweaver#151]
**Describe the bug**
When decorating a field with RelationshipField, if the target of the relationship has a different name in its type-graphql ObjectType decorator from its `.name` property, the backend will fail with:

```Error: Cannot determine GraphQL input type for argument named 'filter' of 'entityOne' of 'EntityTwo' class. Is the value, that is used as its TS type or explicit type, decorated with a proper decorator or is it a proper input value?"```

**To Reproduce**
Create two entities in this form:

```
@ObjectType("One")
class EntityOne {
   ...
}

@ObjectType()
class EntityTwo {
   @RelationshipField(() => EntityOne, { id: 'entityOneId' })
   entityOne!: EntityOne;
}
```

The base resolver will create a filter `OnesFilter` using the name from the ObjectType decorator.
The RelationshipField decorator will attempt to create a filter field using the type name `EntityOnesFilter` from the class name.

**Comment by skeep-exogee** [comment]
We will look to improve this one in the next sprint, we should check the metadata store for the name.

**Comment by siowhoi** [comment]
Hi @kyelewis, this issue has been fixed. Please try again.
