### ISSUE TITLE
`graphweaver init` UX feedback

### ISSUE THREAD

**Issue by kyelewis** [exogee-technology/graphweaver#153]
Running `graphweaver init`:

- `Initing project undefined, undefined, undefined, undefined, undefined, undefined...` - Lots of undefined

- Command describes a `password`, `host`, `port` and `user` argument but does not use them.

- The `name` argument is ignored if used without `backend` also.

- If the `backend` argument is used with a valid backend but no `name` argument is provided, the prompts run doubled/twice.

- The `backend` argument cannot specify multiple backends, but the interactive flow allows this.

- Missing `database name` argument?

- The `What would your like to call your new project?` prompt is not validated for a valid `package.json` name, and the init fails later if left empty.

- `Make sure you to pnpm install, then pnpm start.` - The word `to` should change to `run`?

- `Make sure you to pnpm install, then pnpm start.` - Missing instruction to `cd` in to the project directory first.

- When choosing sqlite, `src/database.ts` has a lot of extra whitespace in it.

- When choosing sqlite, no clear immediate documentation on '%%REPLACE_WITH_DB_NAME%%' or links to other documentation.

**Comment by kyelewis** [comment]
Working on this in https://github.com/exogee-technology/graphweaver/pull/156

**Comment by siowhoi** [comment]
Closing this issue because all the issues have been addressed.
