### ISSUE TITLE
`graphweaver import sqlite` UX feedback

### ISSUE THREAD

**Issue by kyelewis** [exogee-technology/graphweaver#154]
Running `graphweaver import sqlite`:

- If the database file does not exist, a new, empty sqlite database is created with the provided file name, it should cause an error instead.

- `Source: sqlite, Database: Chinook_Sqlite.sqlite, Host: undefined, Port: undefined, User: undefined` - Lots of undefined

- Command overwrites `src/backend/database.ts` changes without warning.

- Command overwrites `src/backend/schema/index.ts` changes without warning.

- If not run in the project root, throws with `Error: Cannot find module '/Users/klewis/git/gw-tests/a/src/package.json'`

**Comment by skeep-exogee** [comment]
Thanks @kyelewis lets add this to this of things to improve 👍

**Comment by siowhoi** [comment]
Thanks @kyelewis for the valuable recommendations! Here are the updates:
1. Fixed. If the database file doesn't exist, the cli prompts for a value, and the database file gets created during the connection establishment.
2. Fixed
3. Please refer to pr #187 for more details.
4. Also, see pr #187 for further context
5. Fixed. The command `graphweaver import sqlite` works on any file location.

Appreciate your feedback, and feel free to let me know if there's anything else.

**Comment by siowhoi** [comment]
Closing this ticket as all issues had been addressed.
