### ISSUE TITLE
`graphweaver import postgresql` UX feedback

### ISSUE THREAD

**Issue by kyelewis** [exogee-technology/graphweaver#155]
- Tables without a primary key will cause a failure on startup: `An error occurred during Apollo Server startup. All GraphQL requests will now fail. The startup error was: MyEntity entity is missing @PrimaryKey()`

**Comment by skeep-exogee** [comment]
Yeah we need to handle this along with composite primary keys. Thanks for raising!

**Comment by siowhoi** [comment]
Thank you for bringing up this issue! 😊

This error message was thrown by Mikro-ORM. I'm sorry to inform you that we won't be able to address it. Currently, we rely on mikro-orm, which requires a primary key in every entity, making this particular issue challenging to handle.

I'm going to go ahead and close this ticket for now. Please don't hesitate to reach out if you have any more questions or if you encounter other issues in the future. While we're using Mikro-ORM at the moment, our tech stack might evolve, so who knows what the future holds! 🚀

Thanks again for your contribution and understanding. 👋
