### ISSUE TITLE
Windows path is not constructed correctly

### ISSUE THREAD

**Issue by thekevinbrown** [exogee-technology/graphweaver#184]
**Describe the bug**
We should be using `path.join()` to construct paths. Currently on Windows 10 we log the following from the CLI:

```
? What would your like to call your new project? test-project
? Which Graphweaver backends will you need? MikroORM - PostgreSQL Backend
? OK, we're ready- I'm going to create a new app in "D:\Users\kevin/test-project" - is that OK? Yes
All Done!
Make sure you cd to the new project directory, then run pnpm install and pnpm start.
```

**To Reproduce**

Follow the Quick Start guide in the docs

**Expected behavior**

We should have been trying to create the project in `D:\Users\kevin\test-project`

**Actual behavior**

We create it in `D:\Users\kevin/test-project`

**Desktop (please complete the following information):**

- Windows Server 2019 Datacenter (version 1809, build 17763.4851)

**Comment by steve-keep** [comment]
Hi @thekevinbrown, good news this has been fixed alongside GIH 183:

https://github.com/exogee-technology/graphweaver/pull/233

If you have any more issues with the CLI on windows please let us know.
