### ISSUE TITLE
Permission Denied when following Quick Start Guide

### ISSUE THREAD

**Issue by thekevinbrown** [exogee-technology/graphweaver#185]
**Describe the bug**
After running `pnpm start` in the `test-project` folder I get:

```
Error: listen EACCES: permission denied ::1:9000
    at Server.setupListenHandle [as _listen2] (node:net:1723:21)
    at listenInCluster (node:net:1788:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1937:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8) {
  code: 'EACCES',
  errno: -4092,
  syscall: 'listen',
  address: '::1',
  port: 9000
}
```

**To Reproduce**

Follow Quick Start guide on Windows 10 in AWS Workspaces.

**Expected behavior**

Expected success, or if that's not possible due to AWS Workspace permissions, we should document this error in the docs and describe what steps a user can take to resolve it.

**Actual behavior**
Error message

**Desktop (please complete the following information):**

- Windows Server 2019 Datacenter (version 1809, build 17763.4851)

**Additional context**
This is running on AWS Workspaces, so the settings might not be standard

**Comment by thekevinbrown** [comment]
Note: this seems niche, only affecting AWS Workspaces, which is probably not a huge concern as I don't know many devs working in that environment, but we should definitely document that this is a thing that can happen to all node TCP servers on Windows.

**Comment by siowhoi** [comment]
Thanks @thekevinbrown for reporting this issue! This issue has already been documented in our records. Therefore, we are closing this ticket. 

If you have any further questions or issues, please feel free to let us know and we'll be happy to assist you.

Thanks again for your contribution to improving our project!
