### ISSUE TITLE
Schema allows nullable mandatory fields

### ISSUE THREAD

**Issue by dylanlt** [exogee-technology/graphweaver#191]
**Describe the bug**
The schema allows a mandatory field to be nullable.

**To Reproduce**
Given a data source schema with fields as follows:

	@Field(() => String)
	approved?: string;

	@Field(() => String, { nullable: true })
	published!: string;

**Expected behavior**
**approved** can be null because it has a "?" but **published** cannot because it has a "!".

**Actual behavior**
**published** can be null but **approved** cannot.

**Screenshots or Screencasts**
If applicable, add screenshots or screencasts to help explain the issue.

**Desktop (please complete the following information):**

- OS and version: MacOS 14.0 M1

**Additional context**

**Comment by steve-keep** [comment]
Hi @dylanlt 

Thanks for reporting this issue. This comes from TypeGraphQL and you can see an in-depth discussion here:

https://github.com/MichalLytek/type-graphql/issues/645

There are three options mentioned in that issue:

1. ! everything. With this I lose all code-time type safety around null checks for these properties.
2. ? everything with nullable: true. With this I have type safety, but have to do a lot of unnecessary null checking. I also have to make client-facing changes to the schema that I don't want to make, and as a result of those changes consumers also have to do the same unnecessary null-checking.
3. Disable strictPropertyInitialization.

None of these are ideal and we will be monitoring the issue above for a solution. 

For our projects, we tend to use `?` with `nullable` for everything optional and then `!` for all other fields.
