### ISSUE TITLE
Importing Postgres entities fails to create Typescript entity code correctly.

### ISSUE THREAD

**Issue by intmainvoid** [exogee-technology/graphweaver#238]
**Describe the bug**
After importing my Postgres entities, then starting the Graphweaver server and navigating to the Admin UI, I get a fatal error. The error messages is:

> Error: Cannot determine GraphQL input type for argument named 'filter' of 'id' of '<EntityName>' class. Is the value, that is used as its TS type or explicit type, decorated with a proper decorator or is it a proper input value?

**To Reproduce**

1. Create a new project using the command: `npx graphweaver@latest init`
2. Follow the prompts to create a new GW project
3. Change current directory to the project directory
4. Run the command: `npx graphweaver@latest import postgresql` to kick off the Postgres importer
5. Follow the prompts to import the specified database
6. Wait until it completes
7. Start Graphweaver by running `pnpm start`
8. Navigate to `http://localhost:9000/` using the browser
9. Observe that the error 502 appears in the browser and that a detailed error appears in the console

**Expected behavior**
The Graphweaver Admin UI appears and shows all the imported entities for the imported database

**Actual behavior**
The browser page is empty apart from the message: `Response not successful: Received status code 502`.

**Screenshots or Screencasts**
![image](https://github.com/exogee-technology/graphweaver/assets/719151/2ee92b42-b7bb-4332-ad81-10420114dc60)
![image](https://github.com/exogee-technology/graphweaver/assets/719151/c525ee79-a136-4421-b7de-5a8df924ef71)
![image](https://github.com/exogee-technology/graphweaver/assets/719151/b93ff3c4-42e0-454d-b13f-26795acde3a9)

**Desktop (please complete the following information):**

- OS and version: MacOS 13.5.2 (22G91)
- Postgres version: Version 2.6.8a (228)
- Node: v20.10.0
- pnpm: 8.10.5

**Additional context**
N/A

**Comment by steve-keep** [comment]
Thanks @intmainvoid for the issue report. 

Would you happen to have an example SQL schema so we can test and fix it?

**Comment by intmainvoid** [comment]
Here's some DDL that sets up a minimal DB repro:
```
CREATE TABLE voyage (
    id BIGSERIAL PRIMARY KEY,
    name character varying(255) NOT NULL
);

CREATE TABLE exporter (
    id BIGSERIAL PRIMARY KEY,
    company character varying(255) NOT NULL
);

CREATE TABLE exporter_voyages (
    exporter_id bigint,
    voyage_id bigint REFERENCES voyage(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT exporter_voyages_pkey PRIMARY KEY (exporter_id, voyage_id)
);
```

**Comment by thekevinbrown** [comment]
I'll rename this issue to more accurately reflect the problem, which is that we have limitations with primary keys currently:

1. All entities are assumed to have a primary key called `id`.
2. We do not support compound primary keys (yet, but it's intended to be supported longer term).
3. We do not support entities without a primary key (yet, but it's intended to be supported longer term).
