### ISSUE TITLE
Postgres importer allows null DB username but then fails to display in the Admin UI

### ISSUE THREAD

**Issue by intmainvoid** [exogee-technology/graphweaver#240]
**Describe the bug**
Failure to supply a Postgres user name when importing entities from Postgres causes the import to succeed (when running on localhost) but an error is then displayed when displaying the Admin UI:

> _Error! no PostgreSQL user name specified in startup packet_

**To Reproduce**

1. Create a new project using the command: npx graphweaver@latest init
2. Follow the prompts to create a new GW project
3. Change current directory to the project directory
4. Run the command: npx graphweaver@latest import postgresql to kick off the Postgres importer
5. Follow the prompts to import the specified database **but when it asks for the DB user, just press "Enter". Don't enter anything**
6. Wait until it completes
7. Start Graphweaver by running pnpm start
8. Navigate to http://localhost:9000/ using the browser
9. Click on one of the entities
10. Observe that the error `Error! no PostgreSQL user name specified in startup packet` appears in the main panel

**Expected behavior**
The rows from the relevant entity are displayed

**Actual behavior**
An error message was displayed: `Error! no PostgreSQL user name specified in startup packet`

**Screenshots or Screencasts**
<img width="1386" alt="image" src="https://github.com/exogee-technology/graphweaver/assets/719151/41144cd8-7454-4845-a755-bc106b5d299e">

**Desktop (please complete the following information):**

- OS and version: MacOS 13.5.2 (22G91)
- Postgres version: Version 2.6.8a (228)
- Node: v20.10.0
- pnpm: 8.10.5

**Additional context**
N/A

**Comment by intmainvoid** [comment]
Recommended resolution: Set `postgres` as the default user. This seems to be what it uses anyway when actually doing the import.

**Comment by agaw** [comment]
This has been fixed as part of the following PR https://github.com/exogee-technology/graphweaver/pull/261, which is included in release 0.2.15 and up.
