### ISSUE TITLE
Postgres importer: IdentifiedReference is deprecated

### ISSUE THREAD

**Issue by intmainvoid** [exogee-technology/graphweaver#241]
**Describe the bug**
A brief but clear and concise description of what the issue is.

**To Reproduce**

1. Create a new project using the command: npx graphweaver@latest init
2. Follow the prompts to create a new GW project
3. Change current directory to the project directory
4. Run the command: npx graphweaver@latest import postgresql to kick off the Postgres importer
5. Follow the prompts to import the specified database
6. Wait until it completes
7. Examine the generated source and observe the deprecation warning

**Expected behavior**
The Mikro ORM class `Ref` is used instead of `IdentifiedReference`

**Actual behavior**
The type `IdentifiedReference` is used for references instead of the latest `Ref`.

**Screenshots or Screencasts**
![image](https://github.com/exogee-technology/graphweaver/assets/719151/07deb393-83a6-48c3-ae0d-cc3bf2d6e32d)

**Desktop (please complete the following information):**

- OS and version: MacOS 13.5.2 (22G91)
- Postgres version: Version 2.6.8a (228)
- Node: v20.10.0
- pnpm: 8.10.5 

**Additional context**

**Comment by thekevinbrown** [comment]
This was resolved in https://github.com/exogee-technology/graphweaver/pull/316
