### ISSUE TITLE
Entity Links do not open details panel

### ISSUE THREAD

**Issue by tnodell** [exogee-technology/graphweaver#249]
**Describe the bug**
Clicking on an entity link opens to the entity's table but does not open the entity's detail panel. This is in spite of the  link being formed correctly

**To Reproduce**

1. Start a Graphweaver instance with a related entity relationship. (Albums in the SQLite DB)
2. Select the related entity (Artist from an album)

**Expected behavior**
The table of the entity type (artists) is opened and detail panel of the selected entity is opened.

**Actual behavior**
The table of the entity type is open but the detail panel is not.

**Screenshots or Screencasts**
If applicable, add screenshots or screencasts to help explain the issue.

**Desktop (please complete the following information):**

- OS and version:
Mac 14.1.1

https://github.com/exogee-technology/graphweaver/assets/81122022/f39c938e-63df-491d-87c0-dd450b0ad71c

**Comment by agaw** [comment]
This is fixed in the 0.2.13 release.
