### ISSUE TITLE
Updating Album in SQLite DB errors

### ISSUE THREAD

**Issue by tnodell** [exogee-technology/graphweaver#250]
**Describe the bug**
When attempting to update an album using the SQLite example database in the end to end tests folder, an error message occurs

**To Reproduce**

1. Create an instance of the SQLite DB in the end to end test folder
2. Attempt to edit an album's name

**Expected behavior**
The album name is edited and saved

**Actual behavior**
An error message appears.

Error Message:
`Error: Variable "$data" got invalid value { id: "1", title: "For Those About To Rock We Salute You 2", artist: { id: "1" }, tracks: [[Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object], [Object]] }; Field "tracks" is not defined by type "AlbumCreateOrUpdateInput".`

**Screenshots or Screencasts**
If applicable, add screenshots or screencasts to help explain the issue.

https://github.com/exogee-technology/graphweaver/assets/81122022/c2a43543-19be-4e1a-8224-6248a6ce82eb

**Desktop (please complete the following information):**

- OS and version:
Mac 14.1.1

**Additional context**
This also occurs when editing genre name, artist name, customer company.

**Comment by agaw** [comment]
Thanks @tnodell, this issue has been fixed in https://github.com/exogee-technology/graphweaver/pull/255.
