### ISSUE TITLE
Postgres Importer: Inconsistent use of Snake Case and Camel Case For Imported Fields Causing Type Errors

### ISSUE THREAD

**Issue by agaw** [exogee-technology/graphweaver#251]
**Describe the bug**
When importing a schema from PostgreSQL, certain one-to-many and many-to-many fields get imported as snake_case rather than the prevailing camelCase pattern. This then causes a type error when the `relatedField` parameter in the `@RelationshipField` decorator expects the field name on the opposite side of the relationship to be in camelCase when it is in snake_case.

**To Reproduce**

1. Follow the "Quick Start" guide to initialise a new Graphweaver project: [Docs Link](https://graphweaver.com/docs/quick-start)
2. Create a new, blank PostgreSQL database and populate it using the following SQL:
```
BEGIN;

CREATE TABLE term_period (
    id BIGSERIAL PRIMARY KEY,
    name character varying(255) NOT NULL,
    start_date date NOT NULL,
    end_date date NOT NULL
);

CREATE TABLE weekly_class (
    id BIGSERIAL PRIMARY KEY,
    time_start time without time zone NOT NULL,
    time_end time without time zone NOT NULL
);

CREATE TABLE weekly_class_term_periods (
    weekly_class_id bigint REFERENCES weekly_class(id) ON DELETE CASCADE ON UPDATE CASCADE,
    term_period_id bigint REFERENCES term_period(id) ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT weekly_class_term_periods_pkey PRIMARY KEY (weekly_class_id, term_period_id)
);

CREATE TABLE weekly_class_occurrence (
    id BIGSERIAL PRIMARY KEY,
    weekly_class_id bigint NOT NULL REFERENCES weekly_class(id) ON UPDATE CASCADE,
    term_period_id bigint NOT NULL REFERENCES term_period(id) ON UPDATE CASCADE,
    day_of_week smallint NOT NULL
);

COMMIT;
```
3. Follow the "Importing A Database" guide to create entity files for the database created in Step 2. [Docs Link](https://graphweaver.com/docs/importing-a-database)

**Expected behavior**
All field names should be in camel case and there should be no TS type errors caused by the resulting incorrect `relatedField` values.

**Actual behavior**
Note the following field naming inconsistencies in the generated files:
entities/postgresql/term-period.ts:
```
	@ManyToMany({ entity: () => WeeklyClass, mappedBy: 'termPeriods' })
	weekly_classes = new Collection<WeeklyClass>(this);

	@OneToMany({ entity: () => WeeklyClassOccurrence, mappedBy: 'termPeriod' })
	weekly_class_occurrences = new Collection<WeeklyClassOccurrence>(this);
```
entities/postgresql/weekly-class.ts:
```
	@OneToMany({ entity: () => WeeklyClassOccurrence, mappedBy: 'weeklyClass' })
	weekly_class_occurrences = new Collection<WeeklyClassOccurrence>(this);
```
schema/term-period/entity:ts
```
	@RelationshipField<WeeklyClass>(() => [WeeklyClass], { relatedField: 'termPeriods' })
	weekly_classes!: WeeklyClass[];

	@RelationshipField<WeeklyClassOccurrence>(() => [WeeklyClassOccurrence], { relatedField: 'termPeriod' })
	weekly_class_occurrences!: WeeklyClassOccurrence[];
```
schema/weekly-class/entity.ts:
```
	@RelationshipField<TermPeriod>(() => [TermPeriod], { relatedField: 'weeklyClasses' })
	termPeriods!: TermPeriod[];
```

**Desktop (please complete the following information):**

- OS and version: MacOS Sonoma 14.2.1 (23C71)

**Comment by steve-keep** [comment]
This is now resolved as part of PR: 314.
