### ISSUE TITLE
Custom fields only see first item of 1-n relationships

### ISSUE THREAD

**Issue by dylanlt** [exogee-technology/graphweaver#269]
**Describe the bug**
When creating a custom field (form) component for a one-to-many relationship field, the array of items only contains one item.

**To Reproduce**

1. use a database data source with a 1-n relationship between 2 tables
2. create a custom field admin-ui component "component.tsx"
3. import { useComponentQuery } from './component.generated';
4. pnpm build & pnpm start
5. log the returned data from useComponentQuery()
6. copy the ComponentDocument GQL from component.generated.ts and run in Apollo studio

**Expected behavior**
The useComponentQuery() returns the same result as running the ComponentDocument GQL.

**Actual behavior**
The useComponentQuery() only has one data item but the GQL returns all the expected items.

**Desktop (please complete the following information):**

- OS and version: MacOS 14.2.1 (M1 ARM)

**Comment by thekevinbrown** [comment]
I'm not able to reproduce this. I added a tasks field on users in the rest example https://github.com/exogee-technology/graphweaver/tree/fix/gh-269 and the custom field I added there is logging all of the user's tasks. Can you edit that reproduction such that we can see the issue?

**Comment by dylanlt** [comment]
I have look at the branch it was missing the GQL for step 3: you will need to add a GQL query into the component in order for the build to generate './component.generated'

**Comment by thekevinbrown** [comment]
Still can't reproduce. I updated the branch to use a GraphQL query in the custom component. Works fine:

![Screenshot 2024-02-01 at 2 54 24 pm](https://github.com/exogee-technology/graphweaver/assets/1531750/c8270586-8d6a-4784-bf24-734e8c7a4cdb)

**Comment by thekevinbrown** [comment]
For anyone coming here from Google, what was happening here was the custom component did not query the `id` field of the entity in the custom component. Because of how the [Apollo InMemoryCache](https://www.apollographql.com/docs/react/caching/cache-configuration/) works, these were then collapsed to a single item. The fix in this case was just making sure `id` was on the query.
