### ISSUE TITLE
Can't create new entity with numerical field using the Admin UI

### ISSUE THREAD

**Issue by mackcheesman** [exogee-technology/graphweaver#270]
**Describe the bug**
I can't use the Admin UI to create a new entity with a number field type - it formats any input, regardless of whether it is numerical or not, as a string.

**To Reproduce**

1. Initialised a new GraphWeaver project using `npx graphweaver@latest init`
2. Selected the MikroORM postgres option during setup
3. Switched into my new project directory and ran `pnpm install`
4. Created a new local database with a single 'users' table, slightly altered from the [Connect to PostgreSQL example](https://graphweaver.com/docs/connect-to-a-postgresql-db) - using the DDL below:
```
CREATE TABLE users (
    id integer GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    username text NOT NULL UNIQUE,
    email text NOT NULL UNIQUE,
    age integer,
    display_name text
);

CREATE UNIQUE INDEX untitled_table_pkey ON users(id int4_ops);
CREATE UNIQUE INDEX untitled_table_username_key ON users(username text_ops);
CREATE UNIQUE INDEX untitled_table_email_key ON users(email text_ops);
```
5. Pre-populated my new table with two example users
6. Connected my new database by running `npx graphweaver@latest import postgresql` and providing the connection information
7. Ran `pnpm start`
8. Accessed the Admin UI from localhost:9000
9. Selected 'User' under `mikro-orm-postgresql` 
10. Clicked 'Create New User' in the top left corner
11. Filled out my four fields with example input and clicked 'Save'

**Expected behavior**
I expected a new User entity to be created and then visible from the input I gave.

**Actual behavior**
No new user was created, instead an error appeared reading: `Error: Variable "$data" got invalid value "20" at "data.age"; Float cannot represent non numeric value: "20"`
The response code of the XHR request was also 200, despite the error response.

**Screenshots or Screencasts**
<img width="1715" alt="Screenshot 2024-01-17 at 11 11 16 am" src="https://github.com/exogee-technology/graphweaver/assets/112445159/5e2ccaec-928e-4967-96b7-aca2ad3970ff">

**Desktop (please complete the following information):**

- OS and version: MacOS 14.2.1 (M1)

**Additional context**
After clearing the 'age' input field and trying to click Save again, it still didn't work - I got the same error message, but this time for an empty string.

However, closing the form, re-opening it and trying to submit again **without** ever touching the age input box worked as expected.

The body of the outgoing request when I tried to click Save:
```
{
  "operationName": "createEntity",
  "variables": {
    "data": {
      "username": "anchovyy",
      "email": "mack@thecheesmans.com",
      "age": "20",
      "displayName": "Anchovy"
    }
  },
  "query": "mutation createEntity($data: UserInsertInput!) {\n  createUser(data: $data) {\n    id\n    id\n    username\n    email\n    age\n    displayName\n    __typename\n  }\n}"
}
```

I was able to also get this request to work without producing an error by modifying the "age" field to be the number 20, not the string 20.

**Comment by steve-keep** [comment]
This has been addressed in https://github.com/exogee-technology/graphweaver/pull/313 and will appear in the 0.2.19 release.
