### ISSUE TITLE
Version mismatch on mikro-orm for sqlite

### ISSUE THREAD

**Issue by skorov** [exogee-technology/graphweaver#775]
**Describe the bug**
The initial project folder created by graphweaver has a version mismatch between mikro-orm and it's plugins. This causes an error when trying to import a sqlite database.

**To Reproduce**

1. Follow the instructions here <https://graphweaver.com/docs/quick-start>
2. Follow the instructions here <https://graphweaver.com/docs/connect-to-sqlite>
3. Should see the error while importing the database

**Expected behavior**
No error and the database imports successfully

**Actual behavior**
The following error occurs:

```
root@a88af515fadc:/volkis_test# npx graphweaver@latest import sqlite --database=Chinook_Sqlite.sqlite --host localhost
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
Importing data source...
Source: sqlite
Database Name: Chinook_Sqlite.sqlite
Database Host: localhost

(node:641) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
⠋ Introspecting...

Warning: Unable to connect to database.
Bad @mikro-orm/knex version 6.2.8.
All official @mikro-orm/* packages need to have the exact same version as @mikro-orm/core (6.2.9).
Only exceptions are packages that don't live in the 'mikro-orm' repository: nestjs, sql-highlighter, mongo-highlighter.
Maybe you want to check, or regenerate your yarn.lock or package-lock.json file?
```

**Desktop:**

- OS and version: Debian 12 running Docker node@latest

**Additional context**
Seems like a bump to version 6.2.9 in the package.json template fixes the issue.

Specifically, the `MIKRO_ORM_TARGET_VERSION` variable in `/src/packages/cli/src/init/constants.ts`

**Comment by thekevinbrown** [comment]
Thanks for reporting, we'll cut a release shortly!

**Comment by thekevinbrown** [comment]
Version 1.0.1 is out, which we believe will fix this issue. If you hit any new ones just let us know!
