### ISSUE TITLE
Unknown entityName undefined

### ISSUE THREAD

**Issue by dylanlt** [exogee-technology/graphweaver#93]
**Describe the bug**
The administration site shows the message "Unknown entityName undefined" when I try to open http://localhost:9000/

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up a graphweaver project *
2. pnpm start
3. Open http://localhost:9000

* note: I have several data providers, but this message was not appearing until now. As far as I am aware, there are no changes in the data. I can share code in a private channel.

**Expected behaviour**
The administration interface should appear.

**Actual behaviour**
The site shows the message "Unknown entityName undefined" 

**Screenshots or Screencasts**
![image](https://github.com/exogee-technology/graphweaver/assets/7636222/5634e853-d59c-4b6d-b786-c07274b4f65e)

**Desktop (please complete the following information):**
 - OS and version: Mac M1 OS 13.4

**Additional context**
n/a

**Comment by kyelewis** [comment]
Adding context- this seems to happen in the Admin UI Metadata resolver when using arrays- if the array is not of an entity but instead of a basic type like String or a scalar.

**Comment by skeep-exogee** [comment]
Hi @dylanlt thanks for logging this issue.

We looked into it and have fixed in this PR:

https://github.com/exogee-technology/graphweaver/pull/96
